### ISSUE TITLE
Add Deep Learning models

### ISSUE THREAD

**Issue by JackJJCodes** [DSCVITBHOPAL/ML-Reserve#10]
Add notebooks/scripts that show implementation of various Deep Learning algorithms!

**Comment by AnikaJagati** [comment]
Hey, I would like to contribute by adding a deep learning cnn classification on gemstones dataset done using pytorch.

**Comment by JackJJCodes** [comment]
Go ahead @AnikaJagati!. 
The method to contribute is given in the README file. Feel free to ask if you have any doubts!

**Comment by AnikaJagati** [comment]
> Go ahead @AnikaJagati!. The method to contribute is given in the README file. Feel free to ask if you have any doubts!

Hey !
I've also added the code implementation for the same and raised a pull request.
Do review and merge it , if it satisfies all the parameters

Thanks! :)

**Comment by pavi-ninjaac** [comment]
@JackJJCodes i would like to add the real time face emotion recognition from web cam using DL. How about his ? can i ?

**Comment by JackJJCodes** [comment]
@pavi-ninjaac Yes you can. 
Please make sure to follow the folder structure, and you'll be fine!

**Comment by Shreyashmohadikar** [comment]
Hey!! I would like to contribute by adding a deep learning model on implementation of the CIFAR10 dataset using TensorFlow & Keras Sequential API
