### ISSUE TITLE
Hand Gesture Recognition

### ISSUE THREAD

**Issue by ritweekraj2802** [DSCVITBHOPAL/ML-Reserve#22]
Recognizing "Hand Gestures" using OpenCV and Python.

Libraries :
cv2
imutils
numpy
sklearn

Please assign this to me.
Thank you

**Comment by JackJJCodes** [comment]
Hey @ritweekraj2802! Will assign you this issue.
Please make sure to follow the folder structure.

**Comment by AM1CODES** [comment]
Issue solved with #24
