### ISSUE TITLE
CartPole Balancing

### ISSUE THREAD

**Issue by Sidhved** [DSCVITBHOPAL/ML-Reserve#25]
---

Title: CartPole using DQN
About: Reinforcement Learning - Deep Q-Network
Name: Sidhved
Label: Feature Request
---

Define You:

- [X] Hacktoberfest2021 Participant 
- [ ] Contributor

**Is your feature request related to a problem? **
CartPole problem is the problem of balancing the CartPole. CartPole is the structure where a pole is attached to the cart and the cart is free to slide across the frictionless surface. By sliding the cart left or right, the CartPole is balanced.

**Describe the solution you'd like...**

Using Deep Q-Network, we will simulate the Cartpole Balancing. With each iteration, the agent is rewarded/punished based on the performance until we reach maximum high score and minimum exploration rate 

**Library Requirement**

- gym
- numpy
- matplotlib
- keras
- collections
- random

**Comment by JackJJCodes** [comment]
Yes @Sidhved. We will assign this to you.
Please maintain the folder structure!

**Comment by AM1CODES** [comment]
If possible please attach some screenshots in the PR as well so that we can get a better idea of the project. Thank you.

**Comment by Sidhved** [comment]
I have added screenshots under objective section in the readme for the project. The images can also be found under resources folder

**Comment by AM1CODES** [comment]
Awesome. That will be great!
