### ISSUE TITLE
Adding projects under Projects Showcase

### ISSUE THREAD

**Issue by itsksquare** [DSCVITBHOPAL/ML-Reserve#26]
Hey, I noticed no projects were listed under Projects Showcase section in the Readme, I could do it for all the projects in the repo currently.
Kindly assign this issue to me so I can start working on adding those projects.

**Comment by AM1CODES** [comment]
Okay, you can go ahead with that. Can you please let me know how you plan to make it? I would suggest doing it in table other wise it will be super long. Just attach a ss in your PR as well, that would help. Assigning this to you.

**Comment by itsksquare** [comment]
I was thinking of doing it like, 
- Name (linking to the folder)
   Small description 
   an image aligned to the right so that it doesn't take up a lot of space

Do you want me to try both the ways, then we can see which looks better?

**Comment by AM1CODES** [comment]
Yea sure. I think that would be great. Go ahead and start working on it.
