### ISSUE TITLE
Mask vs No-mask detection

### ISSUE THREAD

**Issue by dishant26** [DSCVITBHOPAL/ML-Reserve#46]
A script that will take input image from user and give an output image with the detection of faces of people with and without a mask.

I will create a Object Detection Model using YOLOv5 which is trained on Mask vs No-mask images with bounding boxes.
It can detect all the faces in the image with mask and people without mask and create a bounding box around that face with respective label and the confidence percentage.

Please assign me this issue under **hacktoberfest2021**

Example Output:

![126202-untitled-design-13_jpg rf baa3d2e55d469ae5d5d4cd81c4603e1d](https://user-images.githubusercontent.com/64226014/137970131-fa73efd7-a02a-44d4-9581-03603856dd19.jpg)
![10fea_8011463765e2aa28b386cf_jpg rf 7981dc5de795ab4252631683e0de84ae](https://user-images.githubusercontent.com/64226014/137970162-83d254f4-67ca-46db-a86f-4dd63ef79436.jpg)

**Comment by JackJJCodes** [comment]
Looks great @dishant26! Assigning you right away!
