### ISSUE TITLE
Add Machine Learning models

### ISSUE THREAD

**Issue by JackJJCodes** [DSCVITBHOPAL/ML-Reserve#7]
Add notebooks/scripts that show implementation of various ML algorithms!

**Comment by AnikaJagati** [comment]
Hey , I would also like to contribute a simple ML classification implementation done on Breast cancer dataset.

**Comment by JackJJCodes** [comment]
Sure! Go ahead @AnikaJagati!

**Comment by AnikaJagati** [comment]
Hey @JackJJCodes ,
I've added my branch to the forked repo with the code and made a pull request for the same.
Have a look and lemme know :)

**Comment by IshitaSaha3002** [comment]
Hey! I would like to contribute a simple ML Logistic regression problem on Credit Card Fraud Detection, under Hacktoberfest 2021. Can I go ahead with it?
Thanks!

**Comment by JackJJCodes** [comment]
Yes you can definitely go ahead with it @IshitaSaha3002!
Just make sure to follow the folder-structure and you'll be fine!

**Comment by namanarora09** [comment]
How about the room classifier?

**Comment by AM1CODES** [comment]
@namanarora09 its already done so i would suggest add something different and unique. Or if you are interested in deploying that model you can work on that as well.

**Comment by namanarora09** [comment]
Hey, I would like to contribute to Intel Image Classification Challenge. Can I go ahead with it?

**Comment by AM1CODES** [comment]
@namanarora09 what will you contribute to it?
