### ISSUE TITLE
Add end-to-end projects

### ISSUE THREAD

**Issue by JackJJCodes** [DSCVITBHOPAL/ML-Reserve#8]
Add fully-developed projects, that could be used as API's or are stand-alone websites. 
You could use Flask, Django, or any framework that you'd like. 
You can also deploy them on various platforms like Heroku, Render, Azure etc.

**Comment by inspo13** [comment]
Can I  contribute to this issue by deploying a machine learning model on mobiles? 
Like an android app predicting the iris flower species based on sepal and petal length and width using kotlin, android studio and TensorFlow lite.  If you like the idea please assign this to me.
