### ISSUE TITLE
Deployed Flower Classification Model onto a Web App  using Streamlit

### ISSUE THREAD

**Issue by inspo13** [DSCVITBHOPAL/ML-Reserve#87]
Deploy a deep learning Keras model onto a web app using Streamlit.
Upload the image of any flower then the model will predict the correct name of the flower shown in the image.

**Comment by inspo13** [comment]
@JackJJCodes Please assign this to me.

**Comment by AM1CODES** [comment]
Sure assigning this to you.

**Comment by inspo13** [comment]
Ok. Thank you.
