### ISSUE TITLE
Git clone error

### ISSUE THREAD

**Issue by mayureshagashe2105** [DSCVITBHOPAL/ML-Reserve#89]
![2021-10-31](https://user-images.githubusercontent.com/75118658/139591800-b531f9b8-1317-4c02-a31e-c0e37a4847eb.png)

It seems that, the file name is incompatible with MAC & Windows.
I request project maintainers to check it out once,
Thank you!

**Comment by AM1CODES** [comment]
Sure go ahead with the PR.
