### ISSUE TITLE
Add Python Scripts

### ISSUE THREAD

**Issue by JackJJCodes** [DSCVITBHOPAL/ML-Reserve#9]
Add Python scripts for various things like Automation, Scraping, convertors etc. 
Sky's the limit!

**Comment by kannangr21** [comment]
Where to add scraping scripts? Also can I add any websites data?

**Comment by TheGuyDangerous** [comment]
Hey , can i get it assigned ? its my first contribution and i think i have a python script ready .. to scrape .csv files data from sites if implemented correctly

**Comment by JackJJCodes** [comment]
Hi @TheGuyDangerous!
1. You need to create your own issues.
2. Please put your script in a folder named Python-Scripts, and then make a PR.
Hope this helped!

**Comment by TheGuyDangerous** [comment]
Umm .. last question .. by creating a PR that way .. will it be counted in the hacktober fest too ?

**Comment by JackJJCodes** [comment]
Yes it will be counted.

**Comment by JackJJCodes** [comment]
Hi @ayushpaine! 
Yes, you can add the script. Please make sure to follow the file structure and create your own issue.

**Comment by ayushpaine** [comment]
> @ayushpaine The script looks great! Could make an issue for this PR? I would assign it to you and merge it ASAP.
Done, can you please take a look at it now?
