### ISSUE TITLE
Git Clone Error

### ISSUE THREAD

**Issue by HemanthSai7** [DSCVITBHOPAL/ML-Reserve#98]
![image](https://user-images.githubusercontent.com/73033596/151515681-5e4a96ad-3040-4ec0-b46c-26fa4179a209.png)
![image](https://user-images.githubusercontent.com/73033596/151516867-75575d7f-3ccd-47e0-986d-079f839f9801.png)
Looks like there is issue with one of the directories

**Comment by mayureshagashe2105** [comment]
Collaborators, please assign it to me.

**Comment by mayureshagashe2105** [comment]
#89
